name: Daily Create Branch

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date
        id: date
        run: echo "date=$(TZ=Asia/Tokyo date +'%y%m%d')" >> "$GITHUB_OUTPUT"

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create and push new branch
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          NEW_BRANCH="develop_${{ steps.date.outputs.date }}"
          
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH