name: Create PR to Develop

on:
  push:
    branches:
      - 'milestone_*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create or update PR to develop
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: "Merge ${{ github.ref_name }} into develop"
          body: |
            This pull request was automatically created by GitHub Actions.
            Source branch: `${{ github.ref_name }}`
          delete-branch: true
